.flake8, .gitignore, app/__init__.py, app/ex_functions.py, app/gui.py, requirements.txt
- Pull out GUI to `gui.py`
- Add CLI interface with `click`. Should resolve #26
- Refactor `gui.py` to follow pep8 naming
- Refactor `gui.py` to use `ex_functions` helpers
- Add `flake8` configuration
- Refactor `__init__.py` to follow `flake8` configuration
=> Major refactoring for init

todo_now.md, todos/0.5.md, todos/future.md
- Update future todos. Add 0.6 todos.
=> Update future todos. Add 0.6 todos

README.md, requirements/test.txt
- Fix travis readme links. Add coverage to test requirements
=> Fix travis readme links. Add coverage to test requirements

requirements/test.txt
- Downgrade coverage package to fix coveralls
=> Downgrade coverage package to fix coveralls

.travis.yml, app/database.py, app/forms.py, app/main.py, app/utils.py, app/views/administrate.py, app/views/manage.py, gt_cached.json, installer.sh, templates/base.html, templates/csvs.html, templates/index.html, templates/manage.html, templates/offices.html, templates/sb_manage.html, tests/adminstrate.py, tests/common.py, tests/manage.py, todo_now.md
- Fix task update bug after migrating to Py3
- Add test coverage for task update
- Refactor task update
- Fix `getattr(role)` bug introduced with `HEAD~1`
- Fix update admin unit test
- Add enable/disable headers option on csv export
- Add delimiter options on csv export
- Refactor csv export and add test coverage
=> Add csv export options and Refactor task update

app/database.py, app/views/manage.py, tests/common.py, tests/manage.py
- Refactor manage tasks a bit more
- Add `task_a` test coverage
=> Refactor manage tasks a bit more. Add `task_a` test coverage

app/constants.py, app/gui.py, app/main.py, app/printer.py, app/utils.py, app/views/administrate.py, app/views/customize.py, gt_cached.json, installer.sh, run.spec, tests/common.py
- Fix `r_path` bug after migrating to py3
- Refactor and rename `r_path` to `absolute_path`
- Update `run.spec` for new testing env
- Bump version from `0.5` to `0.6`
- Fix arabic gui tabed text
=> Final refactoring prior to 0.6 release

todo_now.md, todos/0.6.md, todos/future.md
- Update TODOs for 0.7 release
=> Update TODOs for 0.7 release

installer.sh, requirements/main.txt, todo_now.md
- Fix requirements resolves #46 .
- Fix installer tests.
- Add more todos.
=> Fix requirements resolves #46 . Fix installer tests. Add more todos.

.gitignore, installer.sh, tests/common.py, tests/manage.py
- Add fill tickets to tests life-cycle
- Add check tickets migration to update common task test
- Update `installer.sh` to use `Python 3.7`
- Add `.vscode` to `.gitignore`
=> Add fill tickets and Housekeeping

app/views/core.py, tests/common.py, tests/core.py
- Fix reset office's tickets bug, should resolve #53
- Add integration tests for reseting
=> Fix reset office and Add test coverage

app/database.py, app/helpers.py, app/views/manage.py, templates/all_offices.html, tests/adminstrate.py, tests/common.py, tests/core.py, tests/manage.py, todo_now.md
- Refactor and add test coverage for manage, all_offices, offices, office_a
=> Refactor and add test coverage for manage, all_offices, offices, office_a

app/database.py, app/views/core.py, app/views/manage.py, tests/common.py, tests/manage.py, todo_now.md
- Refactor the leftovers of manage endpoints
- Add more test coverage for manage endpoints
- Fix all `/task` url to always send office id
=> Minor refactoring and Adding test coverage

app/views/administrate.py, tests/adminstrate.py
- Fix operators office update #59 
- Add test-coverage
=> Fix operators office update #59 and Add test-coverage

app/constants.py, app/database.py, app/helpers.py, app/printer.py, app/views/administrate.py, app/views/core.py, app/views/manage.py, gt_cached.json, static/extFunctions.js, templates/display.html, tests/core.py, tests/manage.py, todo_now.md
- Major `core` endpoints refactoring and Add test coverage
=> Major `core` endpoints refactoring and Add test coverage

app/views/core.py
- Fix missing prefix in `core.feed`, resolves #67
=> Fix missing prefix in `core.feed`, resolves #67

app/tasks.py, app/utils.py
- Add check for announcement status in caching task, resolves #72
- Add print to `log_error`
- Add `log_error` and error handling to caching task
=> Check if announcement is enabled before caching, resolves #72

app/__init__.py, app/constants.py, app/main.py
- Avoid migration if database file does not exist, resolves #77
=> Avoid migration if database file does not exist, resolves #77

requirements/main.txt, templates/base.html
- Update flask_googletrans to 0.10 and failsafe it, resolves #83
=> Update flask_googletrans to 0.10 and failsafe it, resolves #83

README.md, app/database.py, app/main.py, installer.sh, todo_now.md
- Cleanup and refactor `installer.sh`
- Fix `video` settings default to enabled
- Fix migration always throw exception on windows
- Cleanup and refactor `README`
=> Final cleanups and fixes for 0.7 release

README.md, run.spec
- Add python logger to pyinstaller hidden imports
- Reorder sections in `README`
=> Add python logger to pyinstaller hidden imports

app/constants.py, run.spec
- Update version to 0.7 and Fix pyinstaller logger hidden import.
=> Update version to 0.7 and Fix pyinstaller logger hidden import.

README.md
- Update migration instructions to include multimedia files
=> Update migration instructions to include multimedia files

README.md, installer.sh
- Add py3.7 required to instructions and `installer.sh`
=> Add py3.7 required to instructions and `installer.sh`

app/printer.py, app/views/core.py, gt_cached.json
=> Fix printer false parameters and failsafe ticket

.flake8, .pep8, .travis.yml, installer.sh, requirements/main.txt, tests/adminstrate.py, tests/common.py, tests/conftest.py, tests/core.py, tests/manage.py, tests/printer.py
- Fix py.test dynamic fixtures
- Fix tests linting errors
- Upgrade security outdated bleach and Pillow versions
=> Refactor tests and dependencies

app/database.py, app/helpers.py, app/views/customize.py, tests/common.py, tests/customize.py
- Refactor `customize.py` legacy code
- Add test coverage for `customize.py`
- Add some helpers
- Fix yesterday's refactoring bugs 🤦‍♂️. resolves #119 #118 #115 #112
=> Minor customize refactoring and bug fixes

app/printer.py, app/views/core.py, app/views/customize.py, requirements/deploy.txt, tests/common.py, tests/core.py, tests/customize.py
- Fix Linux Printing and Add printing test coverage. Resolves #122
- Bump `MarkupSafe` in `deploy.txt` to match `main.txt`
=> Fix Linux Printing and Add printing test coverage.

app/main.py, app/tasks/tickets.py, app/utils.py, tests/common.py, tests/core.py, tests/utils.py
- Resolves #113
- Resolves #105
=> Add create alternative db session.

gt_cached.json, static/tts.json
=> Add German and Urdu TTS support.

.flake8, app/database.py, app/helpers.py, app/settings.py, app/views/core.py, app/views/manage.py, gt_cached.json, migrations/versions/2ea95f7d541c_.py, templates/all_offices.html, templates/base.html, templates/display.html, templates/index.html, templates/manage.html, templates/sb_manage.html, tests/settings.py
For more context and explanation checkout https://github.com/mrf345/FQM/issues/96#issuecomment-636467706
**Single row queuing demo**:
=> Add single row setup. Resolves #96

app/main.py, app/tasks/tickets.py, app/utils.py, tests/common.py
=> Disable db same thread check, add tasks empty db failsafe.

app/database.py, app/forms.py, app/views/core.py, app/views/manage.py, gt_cached.json, migrations/versions/27a835cae9b9_.py, templates/task_add.html, templates/tasks.html
=> Add hidden tasks option. Resolves #170

app/middleware.py, requirements/deploy.txt, requirements/main.txt, templates/display.html
Fix handle Flask-gTTS errors with no internet, Resolves #198
=> Fix handle Flask-gTTS errors with no internet, Resolves #198

templates/display.html
Hide auto_play warning if notification's disabled. Resolves #200
=> Hide auto_play warning if notification's disabled.

app/constants.py, app/database.py, app/forms/manage.py, app/main.py, app/views/manage.py, gt_cached.json, migrations/versions/ec3035d61f8b_.py, templates/_footers.html, templates/_tickets.html, templates/all_offices.html, templates/offices.html, templates/tasks.html, tests/manage.py
Add ticket status and allow updating tickets through the management view. Resolves #137 
<hr />
**Description**: Feature to allow Admins, monitors, and office operators to update any ticket status, value, and type.
**Demo**:
=> Add ticket status and allow updating tickets through the management view.

app/database.py, app/views/administrate.py, app/views/manage.py, templates/sb_manage.html
Fix Management sidebar index disorder, Resolves #207
=> Fix Management sidebar index disorder, Resolves #207

app/database.py, app/forms/customize.py, app/views/core.py, app/views/customize.py, gt_cached.json, migrations/versions/69efa7247067_.py, templates/display_screen.html, tests/customize.py
Add Display Screen Customization option to hide ticket index number, Resolves #188
<hr />
**Demo**:
=> Add option to hide ticket index number, Resolves #188

app/__init__.py, app/constants.py, app/main.py, app/middleware.py, app/tasks/base.py, app/tasks/tickets.py, gt_cached.json, requirements/deploy.txt, requirements/main.txt
Add support for gunicorn, and optimize performance. Resolves #217 #218
=> Add support for gunicorn, and optimize performance.

app/constants.py, app/database.py, app/forms/constents.py, app/forms/customize.py, app/main.py, app/tasks/__init__.py, app/tasks/base.py, app/tasks/cache_tickets_tts.py, app/tasks/delete_tickets.py, app/utils.py, app/views/customize.py, gt_cached.json, migrations/versions/8da7405903f6_.py, requirements/deploy.txt, requirements/main.txt, templates/background_tasks.html, templates/customize.html, templates/sb_cust.html, templates/sb_dis.html, templates/sb_touch.html, tests/__init__.py, tests/conftest.py, tests/core.py, tests/customize.py, tests/settings.py
Add background tasks, And refactor existing tasks. Resolves #199 
<hr />
**Description**: Background tasks will allow us to control and automate some repetitive processes like resetting tickets and caching announcements.
**Demo**:
=> Add background tasks, And refactor existing tasks. Resolves #199

app/api/__init__.py, app/api/auth.py, app/api/constants.py, app/api/endpoints/tickets.py, app/api/serializers.py, app/api/setup.py, app/constants.py, app/database.py, app/main.py, migrations/versions/cf6ed76ef146_.py, requirements/deploy.txt, requirements/main.txt, tests/conftest.py, tests/customize.py
Add API base module and boilerplate. Resolves #181 Resolves #182
<hr />
**Description**: Add the base for an API for FQM. Now we'll be able to access it through http://127.0.0.1:8080/api/v1
**Demo**:
=> Add API base module and boilerplate. Resolves #181 #182

app/api/auth.py, app/database.py, app/forms/adminstrate.py, app/main.py, app/utils.py, app/views/administrate.py, gt_cached.json, static/extFunctions.js, templates/_admin.html, templates/auth_tokens.html, templates/base.html, tests/__init__.py, tests/adminstrate.py
Add interface to handle CRUD API tokens. Resolves #183
<hr/>
**Demo**:
=> Add interface to handle CRUD API tokens. Resolves #183

app/database.py, app/printer.py, app/utils.py, gt_cached.json, tests/views/core.py
Fix printed tickets aliases always ignored. Resolves #229
=> Fix printed tickets aliases always ignored. Resolves #229

app/constants.py, app/database.py, app/helpers.py, app/views/manage.py, gt_cached.json, static/extFunctions.js, templates/_tickets.html, templates/all_offices.html, templates/offices.html, templates/tasks.html
Add tickets order-by option, Resolves #238 
**Demo**:
=> Add tickets order-by option

requirements/main.txt
=> Bump gTTS, PyYaml, and bleach

README.md, app/__init__.py, app/cli.py, app/database.py, app/gui.py, tests/cli.py
Resolves #235 ,
**TODO** : `googletrans` seems to be broken https://github.com/ssut/py-googletrans/issues/234, find an alternative or add the translations manually.
**Demo**:
=> Add reset admin's password option

app/events.py, app/helpers.py, app/main.py, app/utils.py, templates/sb_manage.html
=> fix: operator on start bug

templates/_wallpapers.js, templates/base.html
=> fix: disable online wallpapers script

gt_cached.json
=> Update french translation

app/cache.py, app/events.py, app/views/core.py, app/views/manage.py
Could be related to #298
Resolves #310
=> Fix tickets cache change detection
